import { Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { Provider } from "../components/ui/provider";

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const poppins = Poppins({
	variable: "--font-poppins",
	subsets: ["latin"],
	weight: ["400", "600", "700"],
});

export const metadata = {
	title: "Onde Assistir...",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`
          ${geistMono.variable} 
          ${poppins.variable} 
          antialiased font-sans
        `}
			>
				<Provider>{children}</Provider>
			</body>
		</html>
	);
}
